### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: 'data/models/vg-encoder-5-3000.pkl'

### ISSUE THREAD

**Issue by MuhamedAsh** [reubenharry/Recurrent-RSA#1]
Hi,

I am trying to run main.py and I get this error. 

Traceback (most recent call last):

  File "<ipython-input-6-4097c9cd2d5a>", line 1, in <module>
    runfile('C:/Users/maaVI/Recurrent-RSA/main.py', wdir='C:/Users/maaVI/Recurrent-RSA')

  File "C:\Users\maaVI\AppData\Local\conda\conda\envs\nightly2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\maaVI\AppData\Local\conda\conda\envs\nightly2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/maaVI/Recurrent-RSA/main.py", line 39, in <module>
    speaker_model.initialize_speakers(model)

  File "C:\Users\maaVI\Recurrent-RSA\bayesian_agents\joint_rsa.py", line 45, in initialize_speakers
    dictionaries=(self.seg2idx,self.idx2seg)) for path in paths]

  File "C:\Users\maaVI\Recurrent-RSA\bayesian_agents\joint_rsa.py", line 45, in <listcomp>
    dictionaries=(self.seg2idx,self.idx2seg)) for path in paths]

  File "C:\Users\maaVI\Recurrent-RSA\train\Model.py", line 46, in __init__
    self.encoder.load_state_dict(torch.load(self.encoder_path,map_location={'cuda:0': 'cpu'}))

  File "C:\Users\maaVI\AppData\Local\conda\conda\envs\nightly2\lib\site-packages\torch\serialization.py", line 301, in load
    f = open(f, 'rb')

FileNotFoundError: [Errno 2] No such file or directory: 'data/models/vg-encoder-5-3000.pkl'

**Comment by reubenharry** [comment]
Are you using git-lfs? If not, git won't download the large model files like  "data/models/vg-encoder-5-3000.pkl"

**Comment by MuhamedAsh** [comment]
Yes, I am using git-lfs and have it initialized. Command was "git lfs clone https://github.com/reubenharry/Recurrent-RSA"
